---
title: "day-2-tasks"
author: "Daniel Kerstan"
date: "8/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(palmerpenguins)
```

# First order univariate derivatives
### A

```{r}
fx <- expression(x^2)

df_dx <- D(expr = fx, name = 'x')

df_dx

x <- 3

eval(expr = df_dx)
```

### B

```{r}
Pa <- expression(2 * (3 * a + 2) ^ 4 - 5)

dP_da <- D(expr = Pa, name = 'a')

dP_da

a <- 1.2

eval(expr = dP_da)

```

## C

```{r}
gt <- expression((-4 * t) / ((t ^ 2 + 1) ^ 3))

dg_dt <- D(expr = gt, name = 't')

t <- 0

eval(expr = dg_dt)


```


# Higher order univariate darivatives

```{r}
Gz <- expression(4.6 - 1.9 * z ^ 3)

dG_dz <- D(expr = Gz, name = 'z')

d2G_dz2 <- D(expr = dG_dz, name = 'z')

d2G_dz2


```

# Partial derivatives

```{r}
fxyz <- expression(2 * x ^ 2 * y - 3 * x + 1 + (4 * z ^ 4 * x))

df_dx <- D(expr = fxyz, name = 'x')

df_dy <- D(expr = fxyz, name = 'y')

df_dz <- D(expr = fxyz, name = 'z')

df_dx
df_dy
df_dz


```


# Make some plots

```{r}
eq <- function(x) {2.4 * exp(-0.05 * x) * sin(x)}

ggplot(data = data.frame(x = c(-0.5, 0.5)), aes(x = x)) + 
         stat_function(fun = eq)
```



```{r}
ggplot(data = penguins, aes(x = bill_length_mm, y = bill_depth_mm)) + geom_point(aes(color = species)) + 
  labs(x = "Bill length (mm)", y = "Bill depth (mm)", title = "Bill depth vs bill length", caption = "Data collected by KB Gorman et al. at Palmer Station")
```


```{r}
ggplot(data = penguins, aes(x = species, y = flipper_length_mm)) + geom_jitter(aes(color = species)) + labs(x = "Species", y = "Flipper length (mm)", title = "Flipper length by species" )
```




